version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@aws-amplify/pubsub"
    versions:
    - 3.2.15
    - 3.2.16
    - 3.2.17
    - 3.2.18
    - 3.2.19
    - 3.2.20
    - 3.2.21
    - 3.2.22
    - 3.2.23
    - 3.2.24
    - 3.2.25
    - 3.2.26
    - 3.2.27
  - dependency-name: "@aws-amplify/api"
    versions:
    - 3.2.17
    - 3.2.18
    - 3.2.19
    - 3.2.20
    - 3.2.21
    - 3.2.22
    - 3.2.23
    - 3.2.24
    - 3.2.25
    - 3.2.26
    - 3.2.27
    - 3.2.28
    - 3.2.29
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
